export enum Permission {
  CoreAccountWrite = 'core:account:write',
  CoreMusicPlay = 'core:music:play',
  GameBet10 = 'game:bet:10',
  GameBet20 = 'game:bet:20',
  GameBet50 = 'game:bet:50',
  GameBet100 = 'game:bet:100',
  GameBet200 = 'game:bet:200',
  GameBet500 = 'game:bet:500',
  GameTypeHalveIt = 'game:type:halveit',
  GameTypeLegs = 'game:type:legs',
  GameTypeLegsClassic = 'game:type:legs-classic',
  GameTypeThree01 = 'game:type:301',
  GameTypeFive01 = 'game:type:501',
}
